### ISSUE TITLE
File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__

### ISSUE THREAD

**Issue by remort** [aio-libs/yarl#485]
Facing this issue with any version of aiohttp starting from 3.4.0 and with recently released yarl 1.5.0.
Using previous yarl==1.4.2 solves this issue (error is gone).
Thought it was old bug bubbling out: https://github.com/aio-libs/aiohttp/issues/1364, but it seems that this issue is new.

**Comment by remort** [comment]
Full trace:

```
Traceback (most recent call last):
  File "/requirements/bin/pytest", line 8, in <module>
    sys.exit(main())
  File "/requirements/_pytest/config/__init__.py", line 73, in main
    config = _prepareconfig(args, plugins)
  File "/requirements/_pytest/config/__init__.py", line 224, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/requirements/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/requirements/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/requirements/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/requirements/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/requirements/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/requirements/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/requirements/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/requirements/_pytest/config/__init__.py", line 794, in pytest_cmdline_parse
    self.parse(args)
  File "/requirements/_pytest/config/__init__.py", line 1000, in parse
    self._preparse(args, addopts=addopts)
  File "/requirements/_pytest/config/__init__.py", line 948, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/requirements/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/requirements/importlib_metadata/__init__.py", line 94, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/requirements/_pytest/assertion/rewrite.py", line 143, in exec_module
    exec(co, module.__dict__)
  File "/requirements/pytest_aiohttp/__init__.py", line 4, in <module>
    from aiohttp.pytest_plugin import *
  File "/requirements/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/requirements/aiohttp/client.py", line 30, in <module>
    from yarl import URL
  File "/requirements/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/requirements/yarl/_url.py", line 56, in <module>
    @rewrite_module
  File "/requirements/yarl/_url.py", line 132, in URL
    _QUERY_PART_QUOTER = _Quoter(safe="?/:@", qs=True, requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```

Packages:
```
aiohttp-3.6.1 aiohttp-cors-0.7.0 yarl-1.5.0
```

Python 3.6

**Comment by DustyArmstrong** [comment]
I have the same issue above, with the same trace back. 

Using previous yarl==1.4.2 solves this issue. 

I am running this in conjunction with Discord.py, on a Raspberry Pi 2.

**Comment by ikegami** [comment]
Same issue using discord.py

```
Traceback (most recent call last):
  File "./numenera_roller.py", line 13, in <module>
    import discord
  File "/home/ikegami/.local/lib/python3.6/site-packages/discord/__init__.py", line 23, in <module>
    from .client import Client
  File "/home/ikegami/.local/lib/python3.6/site-packages/discord/client.py", line 34, in <module>
    import aiohttp
  File "/home/ikegami/.local/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/ikegami/.local/lib/python3.6/site-packages/aiohttp/client.py", line 30, in <module>
    from yarl import URL
  File "/home/ikegami/.local/lib/python3.6/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/home/ikegami/.local/lib/python3.6/site-packages/yarl/_url.py", line 56, in <module>
    @rewrite_module
  File "/home/ikegami/.local/lib/python3.6/site-packages/yarl/_url.py", line 132, in URL
    _QUERY_PART_QUOTER = _Quoter(safe="?/:@", qs=True, requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```
Ubuntu 18.04.4 LTS on Windows Subsystem for Linux (WSL)

**Comment by AHassanSOS** [comment]
I'm getting the same issue with aiohttp

```
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 30, in <module>
    from yarl import URL
  File "/usr/local/lib/python3.6/dist-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/usr/local/lib/python3.6/dist-packages/yarl/_url.py", line 56, in <module>
    @rewrite_module
  File "/usr/local/lib/python3.6/dist-packages/yarl/_url.py", line 132, in URL
    _QUERY_PART_QUOTER = _Quoter(safe="?/:@", qs=True, requote=False)
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```

**Comment by nihaals** [comment]
See [this SO answer](https://stackoverflow.com/a/63161603/7621784).
So far everyone who has had this issue that I've spoken to have been on pip `9.0.1`, which is years out date. Try updating your pip (`pip install -U pip`) and then force reinstalling (`pip install yarl --force-reinstall --no-cache-dir`)

**Comment by nihaals** [comment]
I'm also unable to reproduce this in a docker container. Do you have any consistent repro steps?

**Comment by nihaals** [comment]
You should backup and maybe post a tar of your yarl site-packages folder to help repro before you do this
Try uninstalling yarl, deleting the yarl site-packages folder then installing again

**Comment by ikegami** [comment]
Fixed as follows:

```
mkdir ~/backup
mv ~/.local/lib/python3.6/site-packages/yarl* ~/backup/
pip3 install yarl --force-reinstall --no-cache-dir
```

(`pip3 install -U yarl` would probably have been sufficient.)

---

Original contents of `~/.local/lib/python3.6/site-packages/yarl`:

```
-rw------- 1 ikegami ikegami    154 Jul 30 11:56 __init__.py
-rw------- 1 ikegami ikegami   3536 Jul 30 11:56 __init__.pyi
drwx------ 1 ikegami ikegami   4096 Jul 30 11:56 __pycache__/
-rw------- 1 ikegami ikegami 467308 Jul 28 10:24 _quoting.c
-rwx--x--x 1 ikegami ikegami 544710 Jul 28 10:24 _quoting.cpython-36m-x86_64-linux-gnu.so*
-rw------- 1 ikegami ikegami    519 Jul 30 11:56 _quoting.py
-rw------- 1 ikegami ikegami  11701 Jul 28 10:24 _quoting.pyx
-rw------- 1 ikegami ikegami 476396 Jul 30 11:56 _quoting_c.c
-rwx--x--x 1 ikegami ikegami 570989 Jul 30 11:56 _quoting_c.cpython-36m-x86_64-linux-gnu.so*
-rw------- 1 ikegami ikegami    447 Jul 30 11:56 _quoting_c.pyi
-rw------- 1 ikegami ikegami  11812 Jul 30 11:56 _quoting_c.pyx
-rw------- 1 ikegami ikegami   6516 Jul 30 11:56 _quoting_py.py
-rw------- 1 ikegami ikegami  34589 Jul 30 11:56 _url.py
-rw------- 1 ikegami ikegami     13 Jul 30 11:56 py.typed
-rw------- 1 ikegami ikegami   6856 Jul 28 10:24 quoting.py
```

Correct contents of `~/.local/lib/python3.6/site-packages/yarl`:

```
-rw------- 1 ikegami ikegami    154 Jul 30 11:56 __init__.py
-rw------- 1 ikegami ikegami   3536 Jul 30 11:56 __init__.pyi
drwx------ 1 ikegami ikegami   4096 Jul 30 11:56 __pycache__/
-rw------- 1 ikegami ikegami 467308 Jul 28 10:24 _quoting.c
-rwx--x--x 1 ikegami ikegami 544710 Jul 28 10:24 _quoting.cpython-36m-x86_64-linux-gnu.so*
-rw------- 1 ikegami ikegami    519 Jul 30 11:56 _quoting.py
-rw------- 1 ikegami ikegami  11701 Jul 28 10:24 _quoting.pyx
-rw------- 1 ikegami ikegami 476396 Jul 30 11:56 _quoting_c.c
-rwx--x--x 1 ikegami ikegami 570989 Jul 30 11:56 _quoting_c.cpython-36m-x86_64-linux-gnu.so*
-rw------- 1 ikegami ikegami    447 Jul 30 11:56 _quoting_c.pyi
-rw------- 1 ikegami ikegami  11812 Jul 30 11:56 _quoting_c.pyx
-rw------- 1 ikegami ikegami   6516 Jul 30 11:56 _quoting_py.py
-rw------- 1 ikegami ikegami  34589 Jul 30 11:56 _url.py
-rw------- 1 ikegami ikegami     13 Jul 30 11:56 py.typed
-rw------- 1 ikegami ikegami   6856 Jul 28 10:24 quoting.py
```

Let me know if you want more information.

**Comment by nihaals** [comment]
Could you post a tar with the original broken files? Also, your message seems to show the same output

**Comment by ikegami** [comment]
Sorry, copy and paste error. The following are the correct contents:

```
-rw------- 1 ikegami ikegami    154 Jul 30 12:13 __init__.py
-rw------- 1 ikegami ikegami   3536 Jul 30 12:13 __init__.pyi
drwx------ 1 ikegami ikegami   4096 Jul 30 12:13 __pycache__/
-rw------- 1 ikegami ikegami    519 Jul 30 12:13 _quoting.py
-rw------- 1 ikegami ikegami 476396 Jul 30 12:13 _quoting_c.c
-rwx--x--x 1 ikegami ikegami 570989 Jul 30 12:13 _quoting_c.cpython-36m-x86_64-linux-gnu.so*
-rw------- 1 ikegami ikegami    447 Jul 30 12:13 _quoting_c.pyi
-rw------- 1 ikegami ikegami  11812 Jul 30 12:13 _quoting_c.pyx
-rw------- 1 ikegami ikegami   6516 Jul 30 12:13 _quoting_py.py
-rw------- 1 ikegami ikegami  34589 Jul 30 12:13 _url.py
-rw------- 1 ikegami ikegami     13 Jul 30 12:13 py.typed
```

Will create the requested archive immediately.

**Comment by nihaals** [comment]
CC @Harmon758

**Comment by ikegami** [comment]
http://www.adaelis.com/misc/temp/yarl_issue_485.tar.gz @nihaals

**Comment by nihaals** [comment]
[yarl_issue_485.tar.gz](https://github.com/aio-libs/yarl/files/5002491/yarl_issue_485.tar.gz)
Just to have it on GitHub

**Comment by ikegami** [comment]
Ah, did not know I could do that. I'll remove it from my server.

**Comment by nihaals** [comment]
Did you update your pip after updating to 1.5.0?

**Comment by webknjaz** [comment]
Have you tried wiping the pip cache?

**Comment by ikegami** [comment]
> Did you update your pip after updating to 1.5.0 or before?

After I started having problems, so after updating to 1.5.0 @nihaals 

> Have you tried wiping the pip cache?

No. No idea what that means. @webknjaz

(I've literally written one program in Python.)

**Comment by remort** [comment]
I was rebuilding containers and packages were downloading and building from scratch. Container is based on alpine-3.6 image.

**Comment by webknjaz** [comment]
> No. No idea what that means. @webknjaz

```console
rm -rf ~/.cache/pip
```

**Comment by webknjaz** [comment]
Ah, I see what's happening here:
```console
$ wget https://github.com/aio-libs/yarl/releases/download/v1.5.0/yarl-1.5.0-cp36-cp36m-manylinux1_x86_64.whl
[...]
Saving to: ‘yarl-1.5.0-cp36-cp36m-manylinux1_x86_64.whl’

yarl-1.5.0-cp36-cp3 100%[=================>] 251.50K   565KB/s    in 0.4s

2020-07-31 12:38:08 (565 KB/s) - ‘yarl-1.5.0-cp36-cp36m-manylinux1_x86_64.whl’ saved [257534/257534]

$ wheel unpack yarl-1.5.0-cp36-cp36m-manylinux1_x86_64.whl Unpacking to: ./yarl-1.5.0...OK

$ ls -l yarl-1.5.0/yarl/
total 1.1M
-rw-r--r-- 1 wk wk  154 Jul 31 12:38 __init__.py
-rw-r--r-- 1 wk wk 3.5K Jul 31 12:38 __init__.pyi
-rw-r--r-- 1 wk wk   13 Jul 31 12:38 py.typed
-rw-r--r-- 1 wk wk 466K Jul 31 12:38 _quoting_c.c
-rw-r--r-- 1 wk wk 558K Jul 31 12:38 _quoting_c.cpython-36m-x86_64-linux-gnu.so
-rw-r--r-- 1 wk wk  447 Jul 31 12:38 _quoting_c.pyi
-rw-r--r-- 1 wk wk  12K Jul 31 12:38 _quoting_c.pyx
-rw-r--r-- 1 wk wk  519 Jul 31 12:38 _quoting.py
-rw-r--r-- 1 wk wk 6.4K Jul 31 12:38 _quoting_py.py
-rw-r--r-- 1 wk wk  34K Jul 31 12:38 _url.py
```

There's just one C-extension shared object being shipped in pre-compiled platform-specific wheel.
It must be related to https://github.com/aio-libs/yarl/pull/483. It appears that @asvetlov has forgotten to update `MANIFEST.in` or something else related to packaging.
Will need to fix that and publish a hotfix release.

**Comment by asvetlov** [comment]
Sorry, guys.
I'll publish the fix ASAP

**Comment by webknjaz** [comment]
@asvetlov feel free to tag me for review, I think you need to also update https://github.com/aio-libs/yarl/blob/88559d4/.gitignore#L95-L96 and drop that Cython-generated C-file from the repo.

**Comment by nihaals** [comment]
@asvetlov When will you be doing a release? Seems like a pretty urgent hotfix

**Comment by asvetlov** [comment]
Just now

**Comment by webknjaz** [comment]
@asvetlov this suggests that there may still be some problems https://github.com/aio-libs/aiohttp/issues/4880#issuecomment-668053279.

@nihaals could you confirm that this has been fixed for you?

**Comment by nihaals** [comment]
The issue is an out of date pip version when installing (every report I've seen has used `9.0.1` when first installing `1.5.0`). I was never able to repro it which I found especially strange since I tried in a docker container using pip 9.0.1, installing 1.4.2, updating to 1.5.0, and still didn't get the error. It seems to be more in-depth than simply an old pip version and updating, but when I saw the PR and comments from members here I assumed you were confident of the source so never shared my findings

**Comment by nihaals** [comment]
@kirknorthrop do you have a MWE dockerfile that can repro this?

**Comment by kirknorthrop** [comment]
OK, so I've tried to replicate this this morning, and I found that if I rebuilt our base docker image (which installs some build tools like gcc, and a set of base requirements) then it is no longer present. The base requirements are all fixed to version, but not all subrequirements are - I've included at the bottom a list of ones that had changed between the two images. Our base docker image is based on `python:3.7-slim`

We then take the base image, immediately upgrade pip (which in the **failing** version took us from `20.1` to `20.2.1`) and install further requirements.

Therefore I'm not very sure at all where the issue came from here, although it does appear to be some sort of failure in upgrading. I can't release the docker image unfortunately as it has a password embedded in it, but I am happy to help trace this as best as I can, and if I can try anything out to help then I will do so.

Packages upgraded in the newer docker image:
```cachetools-4.1.1, certifi-2020.6.20, cffi-1.14.1, cryptography-3.0, google-auth-1.20.0, importlib-metadata-1.7.0, joblib-0.16.0, more-itertools-8.4.0, multidict-4.7.6, py-1.9.0, rsa-4.6, six-1.15.0, typing-extensions-3.7.4.2, urllib3-1.25.10, yarl-1.5.1```

**Comment by asvetlov** [comment]
Talking about the very first bug report (and the following `ls` outputs):
```
  File "yarl/_quoting.pyx", line 192, in yarl._quoting._Quoter.__init__
TypeError: __init__() got an unexpected keyword argument 'requote'
```
The problem is: neither GitHub nor `yarl==1.5.1` has `yarl/_quoting.pyx` file at all.
In yarl 1.5 the file was renamed to `yarl/_quoting_c.pyx`

I have no idea how did you get it honestly.
Version 1.5.0 had some untidiness in archived files though, this problem was fixed with help of @webknjaz

**Comment by kirknorthrop** [comment]
It's all very odd. Sorry for a false report - I'm not sure how it has happened either, given I've spent two hours now failing to replicate it!

**Comment by asvetlov** [comment]
No problem!

**Comment by nihaals** [comment]
I think the file could be there due to an out of date pip version which for some reason either left the file there when updating or it somehow found it and tried adding it. Maybe someone more familiar with pip bug reports would know?

Has anyone with pip 9.0.1 and yarl 1.5.0 updated to 1.5.1 and still had the issue? If updating solved it in this weird case I guess it's fixed, otherwise, may need to get some more insight from someone working on pip and maybe give a notice that anyone who has this issue should uninstall, delete all site-packages folders related to yarl, update pip then install yarl again (hopefully it doesn't come to that)

**Comment by kirknorthrop** [comment]
Here's a dockerfile which seems to do all that, and even includes the exact base docker image we had the issue with... but which still doesn't exhibit that behaviour. (And we were on pip 20.1)

The `-m` way of running python is because that's what our final image does - just in case it made a difference!

```
FROM python@sha256:1a4107b19f36d7749f226439c59bec63fd7aa6dedeb132d43bbb0c761b21634e

RUN pip install pip==9.0.1
RUN pip install yarl==1.4.2
RUN pip freeze

RUN pip install --upgrade pip
RUN pip install aiohttp==3.6.2 yarl==1.5.0
RUN pip freeze

RUN echo "from aiohttp import web\nprint('Hello World')" >> test.py

RUN ["python", "-m", "test"]
```

**Comment by Dziqus** [comment]
Hello. Just want to say I got this error today after updating discord.py to 1.4.1 with yarl 1.5.0 and 1.5.1. I was able to fix it by downloading yarl 1.4.2.

**Comment by webknjaz** [comment]
@Dziqus it'd be great if you could come up with some stable reproducer

**Comment by Harmon758** [comment]
This is late, but since there's still some discord.py users encountering this issue:

Since it's possible that [force reinstalling v1.5.0 even without using the cache can fail](https://github.com/aio-libs/yarl/issues/485#issuecomment-666487279), I think it's plausible that this is because there are files that are mistakenly no longer associated with the library by pip that will not be uninstalled during the reinstall. This means that it's also possible that [upgrading from v1.5.0 to v1.5.1 will not fix the issue](https://github.com/aio-libs/yarl/issues/485#issuecomment-672279510) (see also https://github.com/aio-libs/aiohttp/issues/4880#issuecomment-668053279), since those files will not be uninstalled during the upgrade process either.

Since yarl v1.4.2's MANIFEST.in is correct, **downgrading to v1.4.2 fixes the issue.**
Additionally, **there should be no issue with upgrading to a version > 1.5.0 (e.g. v1.5.1) afterwards**, since the incorrect MANIFEST.in in v1.5.0 would be skipped.

**Comment by webknjaz** [comment]
@Harmon758 I'm pretty sure pip tracks the files correctly unless they are installed with unsupported and discouraged methods like `setup.py install` in which case there's nothing anybody can do about it.

**Comment by Harmon758** [comment]
Even if the MANIFEST.in is incorrect? I'm not sure why else pip would leave the files in place through a reinstall and upgrade.

**Comment by webknjaz** [comment]
@Harmon758 I'm almost sure that pip only installs files listed in the manifest but then it tracks the old release files according to the older manifest so it should be fine.

**Comment by webknjaz** [comment]
Actually, pip doesn't really know about `MANIFEST.in`. There's other files in metadata in wheels. And for sdists, it's setuptools that uses the manifest on the build stage, not pip. Pip would use dist-info/egg-info.
